// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSGRTRfeCjqQYy6TnUGYuqKirX4-TEmIg',
    appId: '1:592703828086:web:09cd125670614a45fcef57',
    messagingSenderId: '592703828086',
    projectId: 'cinehub-882c4',
    authDomain: 'cinehub-882c4.firebaseapp.com',
    storageBucket: 'cinehub-882c4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs83eSn0eSgatdXOkEH0J2ZDbDZajjSOY',
    appId: '1:592703828086:android:7467cb8d0438750ffcef57',
    messagingSenderId: '592703828086',
    projectId: 'cinehub-882c4',
    storageBucket: 'cinehub-882c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzBe3V1zlfBMVToosa5MmX9k7DYWys2mU',
    appId: '1:592703828086:ios:f50a3fc972b14438fcef57',
    messagingSenderId: '592703828086',
    projectId: 'cinehub-882c4',
    storageBucket: 'cinehub-882c4.firebasestorage.app',
    iosBundleId: 'com.example.catalogoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzBe3V1zlfBMVToosa5MmX9k7DYWys2mU',
    appId: '1:592703828086:ios:f50a3fc972b14438fcef57',
    messagingSenderId: '592703828086',
    projectId: 'cinehub-882c4',
    storageBucket: 'cinehub-882c4.firebasestorage.app',
    iosBundleId: 'com.example.catalogoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSGRTRfeCjqQYy6TnUGYuqKirX4-TEmIg',
    appId: '1:592703828086:web:3a82f6b2935914a3fcef57',
    messagingSenderId: '592703828086',
    projectId: 'cinehub-882c4',
    authDomain: 'cinehub-882c4.firebaseapp.com',
    storageBucket: 'cinehub-882c4.firebasestorage.app',
  );
}
